### ISSUE TITLE
Fix repair costs on enhanced equipment

### ISSUE THREAD

**Issue by Beaglerush** [better-modernized-combat/bmod-client#129]
Katz spotted this coming before a playtester complained, but basically, I set the value of enhanced gear too high while forgetting that it would also balloon their repair costs if they get damaged.
The fix should be simple, I just need to lower their foundational cost but increase the price at which actual bases will sell them to you for in order to keep the buy/sell prices high while lowering the repair costs to be sane.
Will get onto this before our next Main update.

**Comment by FJonske** [comment]
I recommend a different fix - we could already do that now, or do it in the future when the system I hope for is actually physically possible, which is probably better. In essence, we could make components invulnerable. The system it'd tie into is the component damage system which disables or disrupts them temporarily, which I think needs client hooks.

For now, especially since rn we have very few bases, just selling the low cost item at a high cost seems reasonable. Just gotta make sure we don't accidentally sell at low cost somewhere else, haha.

**Comment by Beaglerush** [comment]
Fixed with 4ab98876dad8ccc67fbce455b547d0b612d96ad6. All + gear added to markets in the future must consider this new approach and have correctly inflated multipliers on their prices per station they're present on.

**Comment by FJonske** [comment]
Just so its in writing somewhere, what multipliers are we going for, as a default?

**Comment by Beaglerush** [comment]
Sorry, it's not that formulaic. I increased +/++/+++ by 1.5/2/2.5x base item cost for now, but as for multipliers, the civ blasters were set to 30x sale point price for instance but others like Navy are set lower so as not to be absurd. Check market_misc and see, if you're interested

**Comment by FJonske** [comment]
In that case, if I ever am in the position to set a price for anything, I'll just eyeball it to be in the same ballpark.
