### ISSUE TITLE
Higher MG ammo cap

### ISSUE THREAD

**Issue by FJonske** [better-modernized-combat/bmod-client#31]
Played during testing, found the amount somewhat restrictive, especially considering they take up slots that would normally fire near-permanently to take out targets, meaning they, too, might be used against shields more than originally intended. Thoughts from others are appreciated, but I'd just go and up the ammo cap by a factor of 2 or 3 at least, if noone minds.

**Comment by IrateRedKite** [comment]
I'd like to do a balance pass on a few of the special weapons as they exist right now, simply because things like the MGs are very _very_ niche, and as it's been mentioned, there isn't a reason to use things like the PPC over the L Laser right now. Would like to have a discussion about the role of some of these weapons generally so I'll move this into scope.

**Comment by IrateRedKite** [comment]
Marking this as done, as @FJonske has included it in the aux weapon pass.
